#!/bin/bash
echo "Fetching Ring1 Preset..."
rsync -av root@192.168.0.111:Bela/projects/FooSkouPlanet/Presets/Ring1.txt MyBelaCode/projects/FooSkouPlanet/Presets;
echo "Fetching Ring2 Preset..."
rsync -av root@192.168.0.112:Bela/projects/FooSkouPlanet/Presets/Ring2.txt MyBelaCode/projects/FooSkouPlanet/Presets;
echo "Fetching Ring3 Preset..."
rsync -av root@192.168.0.113:Bela/projects/FooSkouPlanet/Presets/Ring3.txt MyBelaCode/projects/FooSkouPlanet/Presets;
echo "Fetching Ring4 Preset..."
rsync -av root@192.168.0.114:Bela/projects/FooSkouPlanet/Presets/Ring4.txt MyBelaCode/projects/FooSkouPlanet/Presets;
echo "Fetching Ring5 Preset..."
rsync -av root@192.168.0.115:Bela/projects/FooSkouPlanet/Presets/Ring5.txt MyBelaCode/projects/FooSkouPlanet/Presets;
echo "Fetching Ring6 Preset..."
rsync -av root@192.168.0.116:Bela/projects/FooSkouPlanet/Presets/Ring6.txt MyBelaCode/projects/FooSkouPlanet/Presets;
echo "Fetching Ring7 Preset..."
rsync -av root@192.168.0.117:Bela/projects/FooSkouPlanet/Presets/Ring7.txt MyBelaCode/projects/FooSkouPlanet/Presets;